### ISSUE TITLE
Feature Request: extend/clone login helper for Honkai

### ISSUE THREAD

**Issue by josesan9** [am-steph/wayscript-login-helper#1]
Hi,

I was looking into the potential of this system being extended to also check for the Honkai daily login event in HoYoLab, but have found no success (mainly due to my lack of knowledge of HoYoLab's API).

I was wondering if you think extending this to also perform the daily login for Honkai would be as simple as changing the URLs to point to the correct endpoints, or if the backend is too different to be reused easily?

I would happily get involved in the development of this if you think it is doable. Thanks

**Comment by am-steph** [comment]
Someone has made a modified version of the genshin one to do the login, theres also still a ton of junk in there, but if you wish you could modify it further and remove whats not needed.
https://wayscript.com/script/--mVdtv9
You can check the wiki for the postman guide regarding what you need in order to perform a 'sign-in' on hoyolab and copy that for the honkai login. All you need really is to look for the request header and check for a response, then put into postman or curl the url with according payload. 
https://github.com/am-steph/wayscript-login-helper/wiki/Postman-Sign-In
